### ISSUE TITLE
PInvokeStackImbalance was detected

### ISSUE THREAD

**Issue by jamescoverdale** [bedefaced/sipdotnet#1]
Hi,

I'm trying to get this working (Win 8.1 x64), ive dropped the windows dll's from your mega link in to the bin folder, however when running the code i'm hitting this exception.

"A call to PInvoke function 'sipdotnet!sipdotnet.Linphone::linphone_core_new' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature."

on this line: `linphoneCore = linphone_core_new(vtablePtr, null, null, IntPtr.Zero);`

Any ideas why?

James.

**Comment by omerts** [comment]
Hello,
I have the above problem, and the suggested solution didn't work for me. Is there anything else I could try?

**Comment by PaulSch** [comment]
I also faced this problem, but when I added the cdecl calling convention to the import it worked ;-)
[DllImport(LIBNAME, CallingConvention = CallingConvention.Cdecl)]
