### ISSUE TITLE
Help for add Ringtone

### ISSUE THREAD

**Issue by viniciusoliveira12** [bedefaced/sipdotnet#10]
As I add call tone, I want to click call to let the user hear what is calling.

**Comment by bedefaced** [comment]
If you need to know when call сomes in, subscribe for "IncomingCallEvent".

**Comment by viniciusoliveira12** [comment]
Okay, thank you very much, but at what point would you have to make this call ?, I do not know if I could provide a simple example code, how to make a call, ringtone and save in an .mp3 file. Thanks a lot for the help.

**Comment by viniciusoliveira12** [comment]
I also have another problem, I make the call ok, but besides the sound that is calling the other person, I can not listen to the other person and the other person can not hear me. When I see the mp3 file, it is recorded the sound of the call, and the voice is ok. Please a little help.

**Comment by viniciusoliveira12** [comment]
![error](https://user-images.githubusercontent.com/23043283/31843113-d912b900-b5b6-11e7-841c-6bd93b3e840e.JPG)

**Comment by bedefaced** [comment]
[Fixed](https://github.com/bedefaced/sipdotnet/tree/dee6997a20a5bed1143e22e65e4ffa4f56a42ded). 

Problem was in obsolete dlls in Linphone SDK for Windows. Use dlls from Linphone Desktop for Windows ([zip](https://github.com/bedefaced/sipdotnet/tree/master/lib)).

Also added especially for you setting _ringtone sound_ (`phone.SetIncomingRingSound(file)`) (notification sound when incoming call arrives) and _ringback sound_ (`phone.SetRingbackSound(file)`) (tones that is heard when we're ringing to remote party). The file must be a wav 16bit linear.

**Comment by viniciusoliveira12** [comment]
Thank you very much, my friend! It worked perfectly, thanks for the help.
