### ISSUE TITLE
Can i  use  the  Binaries dll directly ？ linphone 

### ISSUE THREAD

**Issue by MrsZ** [bedefaced/sipdotnet#12]

**Comment by bedefaced** [comment]
For using library from .NET code you need to copy linphone dlls ([liblinphone and dependencies](https://github.com/bedefaced/sipdotnet#requirements)) to directory with your EXE file or use [Add item](https://msdn.microsoft.com/en-us/library/9f4t9t92(v=vs.100).aspx) dialog in Visual Studio (and select *Copy to Output*: `Copy if newer` or `Copy always` in `Properties` window of added dlls) and then add sipdotnet.dll (or the whole project) to your solution.
