### ISSUE TITLE
hi， the linphone can run in xp system？

### ISSUE THREAD

**Issue by MrsZ** [bedefaced/sipdotnet#13]
when I run this project in xp ， wrong     unable to load  linphone.dll   . I have down the .net framework to 
 3.5 . do you konw how to solved this problem? thx.

**Comment by bedefaced** [comment]
Sorry, linphone (and, accordingly, liblinphone) doesn't support Windows XP ([minimum requirement](http://www.linphone.org/technical-corner/liblinphone/features): Windows Vista), so linphone.dll can not be loaded on this system.
