### ISSUE TITLE
using a different Microphone or Audio steam

### ISSUE THREAD

**Issue by chelvaric** [bedefaced/sipdotnet#17]
is it posible to use a different microphone or boxes on the pc to output the sound or video?

or to get the raw video/audio streams?

**Comment by panagiac** [comment]
bump

**Comment by bedefaced** [comment]
Please, try using `RingerDevice`, `PlaybackDevice`, `CaptureDevice` fields in [*dev*](https://github.com/bedefaced/sipdotnet/tree/dev)-branch.
