### ISSUE TITLE
unable to use library

### ISSUE THREAD

**Issue by alijundi** [bedefaced/sipdotnet#2]
I receive the following message:

A call to PInvoke function 'sipdotnet!sipdotnet.Linphone::linphone_core_new' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.

**Comment by KapteinBabbalas** [comment]
I've been looking for a c# implementation of the encryption library used in the PHP version. Found this https://github.com/langboost/libaxolotl-uwp but, how to actually implement it is another story. https://github.com/Muraad/libaxolotl-net

**Comment by levan89** [comment]
have same problem how fix it?

**Comment by nhanttnhantt** [comment]
Unable to load DLL 'liblinphone': The specified module could not be found. (Exception from HRESULT: 0x8007007E).
How to fix it.

**Comment by bedefaced** [comment]
Fixed in update.
