### ISSUE TITLE
Unable to send and receive chat message

### ISSUE THREAD

**Issue by dillipdala** [bedefaced/sipdotnet#25]
i am trying to implement chat message functionality using linphone library. but there is no chat message functionality. I have no idea, how to implement .

please help me on this .

**Comment by bedefaced** [comment]
Added some experimental chat functionality using [tutorial](http://www.linphone.org/docs/liblinphone/group__chatroom__tuto.html) in [https://github.com/bedefaced/sipdotnet/commit/4bc54eef373849847077c248bbec2200d845ad8a](https://github.com/bedefaced/sipdotnet/commit/4bc54eef373849847077c248bbec2200d845ad8a) (*dev* branch):
* SendMessage
* MessageReceivedEvent
