### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by 3dprogramin** [bedefaced/sipdotnet#26]
System info
-----

- Windows 10
- Visual Studio 2017 Community
- .NET 4.0

Problem
-----
Getting a **System.BadImageFormatException** at runtime.
I'm trying to get this runnig the 3rd time now, but getting the same error all the time.

Here is the error:
![screenshot](https://user-images.githubusercontent.com/36532753/37488337-f99f97e8-289c-11e8-9f66-21d31b9fe7bd.png)

------------

VS is also showing warnings, methods being deprecated:

![screenshot_2](https://user-images.githubusercontent.com/36532753/37488388-18abe8bc-289d-11e8-96a0-5981d89082f0.png)

I've used the linphone DLLs from the repo.

If there's anything I can provide, let me know.

Thanks in advance !

**Comment by sherpya** [comment]
provided linphone dll are 32bit, you need to select debug / release x86

**Comment by 3dprogramin** [comment]
That solved it, thanks a lot !
