### ISSUE TITLE
Invalid From number determined

### ISSUE THREAD

**Issue by MetalMuxa** [bedefaced/sipdotnet#4]
I catched next problem while using library. First one or set of first calls are coming to library correct and have correct "From" number in instance of "Call" class. 
However set of next calls have From address exactly like the last the one call (in fact they are different). 
It looks like some unnecessary caching at first look.

For example:
1. 04.11.2016 18:37:12: 792310115XX
2. 04.11.2016 18:37:36: 792319018XX
3. 04.11.2016 18:46:22: 791393165XX
4. 04.11.2016 18:46:35: 791393165XX
5. 04.11.2016 19:23:59: 791393165XX

Like you can see, last three calls have same From number, but in SIP they all are different. Only call #1, #2 and #3 have correct numbers. Calls #4 and #5 are incorrect.

**Comment by MetalMuxa** [comment]
Temporary solved it by changing 
`            //LinphoneCall existCall = FindCall (call);
to
`            LinphoneCall existCall = null;
in Linphone.cs

Hope it does not break any functionality.

**Comment by bedefaced** [comment]
I suppose this fixed in update.
