### ISSUE TITLE
"System.AccessViolationException" in LinphoneMainLoop

### ISSUE THREAD

**Issue by yaroslav1988** [bedefaced/sipdotnet#6]
Hi!

After starting main linphone loop( class `Linphone`> method `LinphoneMainLoop`) with test code suggested in README i always get an exception
**Attempted to read or write protected memory. This is often an indication that other memory is corrupt.**
when thread tries to invoke  `linphone_core_iterate(linphoneCore)`;  for the first time.

If i ignore this exception and continue execution other linphone_core_iterate calls work without exception. May be there is a problem with thread sync in wrapper? Anyone had same issue?

Any thoughts appreciated, thanks!

**Comment by bedefaced** [comment]
I suppose this fixed in update.
