### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by SenolBalaban** [bedefaced/sipdotnet#7]
Hello 
The links to the binaries of liblinphone are both broke broken. In the current release of libLinphone is no dll called "liblinphone-6.dll" which dll can we use instead?.  mega.co.nz -link is also broken.

I have no GCC experience to compile the binaries for myself.

Thanks.

**Comment by bedefaced** [comment]
Please check updated README (you can use "SDK" version of linphone from [official site](http://www.linphone.org/technical-corner/liblinphone/downloads)).
