### ISSUE TITLE
Help Please!

### ISSUE THREAD

**Issue by viniciusoliveira12** [bedefaced/sipdotnet#9]
How do I add linphone.dll to my C # project in Visual Studio?

When I run my sipdotnet test project, this is appearing to me;

{"Unable to load DLL 'linphone.dll': No se puede encontrar el módulo especificado. (Exception from HRESULT: 0x8007007E)"}

**Comment by bedefaced** [comment]
You need copy linphone dlls ([liblinphone and dependencies](https://github.com/bedefaced/sipdotnet#requirements)) to directory with your EXE file or using [Add item](https://msdn.microsoft.com/en-us/library/9f4t9t92(v=vs.100).aspx) dialog in Visual Studio (and select *Copy to Output*: `Copy if newer` or `Copy always` in `Properties` window of added dlls)

**Comment by viniciusoliveira12** [comment]
Thank you @bedefaced , apparently it worked.
